from pathlib import Path

from kb.graph_colors import render_css, write_css


def test_render_css_contains_theme_graph_colors() -> None:
    css = render_css()
    assert ".theme-dark .graph-view.color-fill" in css
    assert ".theme-light .graph-view.color-fill-unresolved" in css
    assert "#7aa2f7" in css


def test_write_css_creates_parent_directory(tmp_path: Path) -> None:
    output = tmp_path / ".obsidian" / "snippets" / "kb-graph-colors.css"
    write_css(output)
    assert output.is_file()
    assert "Generated by kb-tool" in output.read_text(encoding="utf-8")