from pathlib import Path

from kb.graph_colors import render_css, validate_colors, write_css


def test_render_css_contains_theme_graph_colors() -> None:
    css = render_css()
    assert ".theme-dark .graph-view.color-fill" in css
    assert ".theme-light .graph-view.color-fill-unresolved" in css
    assert "#7aa2f7" in css


def test_write_css_creates_parent_directory(tmp_path: Path) -> None:
    output = tmp_path / ".obsidian" / "snippets" / "kb-graph-colors.css"
    write_css(output)
    assert output.is_file()
    assert "Generated by kb-tool" in output.read_text(encoding="utf-8")


def test_validate_colors_rejects_invalid_hex() -> None:
    import pytest
    with pytest.raises(ValueError, match="#RRGGBB"):
        validate_colors({"dark_node": "red"})


def test_themes_change_generated_palette() -> None:
    from kb.graph_colors import THEMES
    assert "#88c0d0" in render_css(THEMES["nord"])
    assert "#89b4fa" in render_css(THEMES["catppuccin"])


def test_validate_theme_reports_contrast() -> None:
    from kb.graph_colors import THEMES, validate_theme
    rows = validate_theme(THEMES["default"])
    assert len(rows) == 4
    assert all("ratio" in row and "ok" in row for row in rows)


def test_validate_theme_respects_threshold() -> None:
    from kb.graph_colors import THEMES, validate_theme
    assert any(not row["ok"] for row in validate_theme(THEMES["default"], minimum=10))


def test_theme_report_has_context_and_conflicts() -> None:
    from kb.graph_colors import THEMES, theme_report
    report = theme_report(THEMES["nord"])
    assert report["minimum_contrast"] == 2.0
    assert len(report["checks"]) == 4
    assert len(report["conflicts"]) == 4
    assert isinstance(report["ok"], bool)
