"""Generate an Obsidian Graph View color snippet."""

from __future__ import annotations

from pathlib import Path
import re


DEFAULT_COLORS = {
    "dark_node": "#7aa2f7", "light_node": "#2457a6",
    "dark_line": "#414868", "light_line": "#9aa5b1",
    "dark_text": "#c0caf5", "light_text": "#334155",
    "dark_unresolved": "#f7768e", "light_unresolved": "#b42318",
    "dark_tag": "#bb9af7", "light_tag": "#6941c6",
    "dark_attachment": "#73daca", "light_attachment": "#087f5b",
    "dark_highlight": "#e0af68", "light_highlight": "#b54708",
}

THEMES = {
    "default": DEFAULT_COLORS,
    "nord": {
        **DEFAULT_COLORS, "dark_node": "#88c0d0", "light_node": "#2e3440",
        "dark_line": "#4c566a", "light_line": "#d8dee9", "dark_text": "#eceff4",
        "light_text": "#2e3440", "dark_unresolved": "#bf616a", "light_unresolved": "#a94442",
        "dark_tag": "#b48ead", "light_tag": "#815b7b",
    },
    "catppuccin": {
        **DEFAULT_COLORS, "dark_node": "#89b4fa", "light_node": "#1e66f5",
        "dark_line": "#585b70", "light_line": "#9ca0b0", "dark_text": "#cdd6f4",
        "light_text": "#4c4f69", "dark_unresolved": "#f38ba8", "light_unresolved": "#d20f39",
        "dark_tag": "#cba6f7", "light_tag": "#8839ef",
    },
}
HEX_COLOR = re.compile(r"^#[0-9a-fA-F]{6}$")


def validate_colors(colors: dict[str, str]) -> None:
    """Reject unknown keys and malformed six-digit hex colors."""
    unknown = set(colors) - set(DEFAULT_COLORS)
    if unknown:
        raise ValueError(f"unknown graph color(s): {', '.join(sorted(unknown))}")
    invalid = {key for key, value in colors.items() if not HEX_COLOR.fullmatch(value)}
    if invalid:
        raise ValueError("colors must use #RRGGBB: " + ", ".join(sorted(invalid)))
def render_css(colors: dict[str, str] | None = None) -> str:
    """Render CSS classes supported by Obsidian's Graph View plugin."""
    validate_colors(colors or {})
    v = {**DEFAULT_COLORS, **(colors or {})}
    return f"""/* Generated by kb-tool graph-colors. Enable as an Obsidian CSS snippet. */
.theme-dark .graph-view.color-fill {{ color: {v['dark_node']}; }}
.theme-light .graph-view.color-fill {{ color: {v['light_node']}; }}
.theme-dark .graph-view.color-line {{ color: {v['dark_line']}; }}
.theme-light .graph-view.color-line {{ color: {v['light_line']}; }}
.theme-dark .graph-view.color-text {{ color: {v['dark_text']}; }}
.theme-light .graph-view.color-text {{ color: {v['light_text']}; }}
.theme-dark .graph-view.color-fill-unresolved {{ color: {v['dark_unresolved']}; }}
.theme-light .graph-view.color-fill-unresolved {{ color: {v['light_unresolved']}; }}
.theme-dark .graph-view.color-fill-tag {{ color: {v['dark_tag']}; }}
.theme-light .graph-view.color-fill-tag {{ color: {v['light_tag']}; }}
.theme-dark .graph-view.color-fill-attachment {{ color: {v['dark_attachment']}; }}
.theme-light .graph-view.color-fill-attachment {{ color: {v['light_attachment']}; }}
.theme-dark .graph-view.color-fill-highlight,
.theme-dark .graph-view.color-line-highlight {{ color: {v['dark_highlight']}; }}
.theme-light .graph-view.color-fill-highlight,
.theme-light .graph-view.color-line-highlight {{ color: {v['light_highlight']}; }}
"""


def write_css(path: Path, colors: dict[str, str] | None = None) -> Path:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(render_css(colors), encoding="utf-8")
    return path